import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";

const montserrat = Montserrat({
  weight: ["100","200","300","400","500","600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} max-w-screen-2xl mx-auto  antialiased bg-[#0a0a0a] text-white`}
      >
        <main className="min-h-screen">
          <Navbar />
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
